Add UBSan sample
ARM-software/LLVM-embedded-toolchain-for-Arm pull request #174
Opened 2023-01-20 15:35 UTC by voltur01

2023-01-20 16:46 UTC, mplatings requested changes
Can this be added to the list of samples in CMakeLists.txt, to ensure it doesn't bitrot?

2023-01-20 16:46 UTC, mplatings commented on samples/src/cpp-baremetal-semihosting-ubsan/libubsan.cpp
> +}
terminating newline

2023-01-20 16:46 UTC, mplatings commented on samples/src/cpp-baremetal-semihosting-ubsan/libubsan.cpp
> +    #include <stdio.h>
Having includes in an `extern "C"` block seems like something to avoid.

2023-01-20 17:12 UTC, voltur01 commented
Thank you for the review: I fixed the year and added to the list of samples as in the other sample; also updated libubsan.cpp as per your suggestions.

2023-01-23 08:57 UTC, mplatings approved these changes

2023-01-23 09:33 UTC, merged