Add CFI sample
ARM-software/LLVM-embedded-toolchain-for-Arm pull request #175
Opened 2023-01-20 16:36 UTC by voltur01

2023-01-20 16:49 UTC, mplatings requested changes
Can this be added to the list of samples in CMakeLists.txt, to ensure it doesn't bitrot?

2023-01-20 16:49 UTC, mplatings commented on samples/src/cpp-baremetal-semihosting-cfi/Makefile
> +# Copyright (c) 2021, Arm Limited and affiliates.
2023

2023-01-20 17:05 UTC, voltur01 commented
Thanks for the review: I fixed the year and added to the list of samples.

2023-01-23 08:54 UTC, mplatings approved these changes

2023-01-23 09:31 UTC, merged