SDCOMP-65328: skip rand and tls tests
ARM-software/LLVM-embedded-toolchain-for-Arm pull request #406
Opened 2024-03-25 13:34 UTC by sivan-shani

The rand and tls tests are failing, skip them until they are fixed.

2024-03-25 13:53 UTC, voltur01 approved these changes

2024-03-25 17:32 UTC, voltur01 approved these changes

2024-03-25 17:46 UTC, domin144 approved these changes

2024-03-25 20:41 UTC, amilendra requested changes
Please remove SDCOMP numbers from the PR. These do not make sense upstream.

2024-03-26 09:48 UTC, amilendra approved these changes

2024-03-26 09:58 UTC, merged